name: RPM builds for EL8, EL9 and EL10

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-rpms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Creating gpg directory
        run: mkdir -p ~/.gnupg

      - name: Building RPMS
        run: |
          sudo ln -sf /usr/bin/podman /usr/bin/docker
          make all
