name: Build RPMS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Creating mock gpg directory
        run: mkdir -p ~/.gnupg

      - name: Pull Container Images
        run: |
          ln -sf /usr/bin/podman /usr/bin/docker
          podman pull ghcr.io/cloudox-org/cloudox-rpm-builder-test-alma:8
          podman pull ghcr.io/cloudox-org/cloudox-rpm-builder-test-alma:9
          podman pull ghcr.io/cloudox-org/cloudox-rpm-builder-test-alma:10

      - name: Building RPMS
        run: make all
